### ISSUE TITLE
release on frdoid

### ISSUE THREAD

**Issue by jmcclelland** [agileware/au.com.agileware.civicontact#3]
Thanks for releasing the mobile code!

I don't have Google Play installed on my mobile phone so it's hard to install CiviContact. 

Would you consider also releasing it via [f-droid](https://f-droid.org/) - it seems to be the most popular repository of android apps for folks who don't want to install google play. Alternatively, you could provide a direct https download (for example, that's something [signal provides](https://signal.org/android/apk/).

**Comment by agileware-justin** [comment]
@jmcclelland thanks for the suggestion. A release with the APK has been posted to the Releases on this repo, see https://github.com/agileware/au.com.agileware.civicontact/releases/tag/v1.0.1

We will keep the releases on github updated when a new version is published.
