### ISSUE TITLE
When I authenticate for the first time, the app responds with "Some error occured while fetching location types." and the app does not load

### ISSUE THREAD

**Issue by agileware-justin** [agileware/au.com.agileware.civicontact#4]
**Mobile Device (please complete the following information):**
 - Device Hardware: Unknown
 - OS & Version: Android

**CiviCRM / Website Environment (please complete the following information):**
 - Server OS: Ubuntu 18.04.4
 - PHP Version: 7.2.24
- CiviCRM Version: 5.23.4
- Website CMS: Drupal 8.8.4

**Describe the bug**
When I authenticate for the first time, the app responds with "Some error occured while fetching location types." and the app does not load.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the QR code to authenticate
2. App starts loading
3. Error message is displayed
4. App does not complete loading

**Expected behaviour**
App should load.

**Screenshots**
![Screenshot_20200330_115944_au com agileware civicontact](https://user-images.githubusercontent.com/58866555/78319957-0e239f00-75b4-11ea-9ba9-c753debab5d6.jpg)

**Comment by HikerBoricua** [comment]
Commenting here because issue #3 was brought over. In issue #3 @johncronan says "I don't think a new CiviContact profile was created" and I can confirm that one was not created in my installation. No errors in the log.
- Drupal 7.69
- CiciCRM 5.24.2
- PHP 7.1.14
- MySQL 5.6.41-84.1

**Comment by agileware-justin** [comment]
Recommend checking the answer provided on https://github.com/agileware/au.com.agileware.civicontactapi/issues/3#issuecomment-781734170

This may be due to other Address fields being disabled in the localisation of your CiviCRM site.
