### ISSUE TITLE
When I try to authenticate, the app keeps loading but I expect it login

### ISSUE THREAD

**Issue by Dietermartens** [agileware/au.com.agileware.civicontact#5]
**Mobile Device (please complete the following information):**
 - Device Hardware: iPhone 11 & 8
 - OS & Version: IOS 13

**CiviCRM / Website Environment (please complete the following information):**
 - Server OS: Linux
 - PHP Version: PHP 7.3
- CiviCRM Version: 5.22.0
- Website CMS: Drupal

**Describe the bug**
When we try to authenticate our device (IOS devices) the scanner opens, scans the code and closes immediately. The app does nothing after that. When we try it for the second time, it shows a loading icon but nothing happens. It keeps loading. 

The backend logs a GET request which responds with a 200. See screenshot (the cid & cs is redacted).

**Expected behaviour**
The app show an error or log in. 

**Screenshots**
<img width="1214" alt="screen 1" src="https://user-images.githubusercontent.com/10003897/78579042-a7f78000-7830-11ea-9969-b40f19642bb9.png">
![IMG_0773](https://user-images.githubusercontent.com/10003897/78579095-b8a7f600-7830-11ea-95b9-a2b91b7fc94e.PNG)

**Comment by agileware-justin** [comment]
@Dietermartens thanks for the report. What happens when you try to use the authentication URL method to authenticate?

**Comment by Dietermartens** [comment]
Hi @agileware-justin thankx for the feedback! 

When i try the link i get a popup with the message it's an invalid link. I checked a couple of things: the baseurl is correctly set and i regenerated the links (qr) a couple of times in the settings. 
![IMG_0774](https://user-images.githubusercontent.com/10003897/78649735-22221600-78be-11ea-8a65-d3cdbaecd608.PNG)

**Comment by agileware-justin** [comment]
@Dietermartens does this CiviCRM site have a site key set? It's in the civicrm.settings.php and should be generated at install time. See https://github.com/civicrm/civicrm-sysadmin-guide/blob/master/docs/setup/site-key.md

If you check the authentication URL, you should be able to see the authentication checksum token part. If that is missing that would be the problem.

**Comment by Dietermartens** [comment]
@agileware-justin the site key is set in the configuration file. 

This is what the url looks like, without the domain. 
https://civicontact.com.au/login?auth=https%3A%2F%2F{DOMAIN}%2Fcivicrm%2Fcca%2Fauth%3Fcid%3D202%26cs%3De6eb639ccfa50cd498ccc1b102a66f8c_1586249391_120

**Comment by agileware-justin** [comment]
I'm going to mark this as closed since we've tested this on iPhones and it was working, Android works and no other reports of this problem.
